//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-article_tags_relation 
    /// </summary>
	public class article_tags_relationEntityTypeConfiguration :  EntityTypeConfiguration<article_tags_relation>
    {
		public article_tags_relationEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsOptional();
        /// <summary>
        /// 文章ID
        /// </summary>
        Property(s=>s.article_id).IsOptional();
        /// <summary>
        /// 标签ID
        /// </summary>
        Property(s=>s.tag_id).IsOptional();
 
			//配置表名称
			ToTable("dt_article_tags_relation");

		}
    }
}
