//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-article_attribute_field 
    /// </summary>
	public class article_attribute_fieldEntityTypeConfiguration :  EntityTypeConfiguration<article_attribute_field>
    {
		public article_attribute_fieldEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 列名
        /// </summary>
        Property(s=>s.name).IsOptional();
        /// <summary>
        /// 标题
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 控件类型
        /// </summary>
        Property(s=>s.control_type).IsOptional();
        /// <summary>
        /// 字段类型
        /// </summary>
        Property(s=>s.data_type).IsOptional();
        /// <summary>
        /// 字段长度
        /// </summary>
        Property(s=>s.data_length).IsOptional();
        /// <summary>
        /// 小数点位数
        /// </summary>
        Property(s=>s.data_place).IsOptional();
        /// <summary>
        /// 选项列表
        /// </summary>
        Property(s=>s.item_option).IsOptional();
        /// <summary>
        /// 默认值
        /// </summary>
        Property(s=>s.default_value).IsOptional();
        /// <summary>
        /// 是否必填0非必填1必填
        /// </summary>
        Property(s=>s.is_required).IsOptional();
        /// <summary>
        /// 是否密码框
        /// </summary>
        Property(s=>s.is_password).IsOptional();
        /// <summary>
        /// 是否允许HTML
        /// </summary>
        Property(s=>s.is_html).IsOptional();
        /// <summary>
        /// 编辑器类型0标准型1简洁型
        /// </summary>
        Property(s=>s.editor_type).IsOptional();
        /// <summary>
        /// 验证提示信息
        /// </summary>
        Property(s=>s.valid_tip_msg).IsOptional();
        /// <summary>
        /// 验证失败提示信息
        /// </summary>
        Property(s=>s.valid_error_msg).IsOptional();
        /// <summary>
        /// 验证正则表达式
        /// </summary>
        Property(s=>s.valid_pattern).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 系统默认
        /// </summary>
        Property(s=>s.is_sys).IsOptional();
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_article_attribute_field");

		}
    }
}
