//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-article_attach 
    /// </summary>
	public class article_attachEntityTypeConfiguration :  EntityTypeConfiguration<article_attach>
    {
		public article_attachEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsOptional();
        /// <summary>
        /// 文章ID
        /// </summary>
        Property(s=>s.article_id).IsOptional();
        /// <summary>
        /// 文件名
        /// </summary>
        Property(s=>s.file_name).IsOptional();
        /// <summary>
        /// 文件路径
        /// </summary>
        Property(s=>s.file_path).IsOptional();
        /// <summary>
        /// 文件大小(字节)
        /// </summary>
        Property(s=>s.file_size).IsOptional();
        /// <summary>
        /// 文件扩展名
        /// </summary>
        Property(s=>s.file_ext).IsOptional();
        /// <summary>
        /// 下载次数
        /// </summary>
        Property(s=>s.down_num).IsOptional();
        /// <summary>
        /// 积分(正赠送负消费)
        /// </summary>
        Property(s=>s.point).IsOptional();
        /// <summary>
        /// 上传时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_article_attach");

		}
    }
}
