//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-article_category 
    /// </summary>
	public class article_categoryEntityTypeConfiguration :  EntityTypeConfiguration<article_category>
    {
		public article_categoryEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsRequired();
        /// <summary>
        /// 类别标题
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 调用别名
        /// </summary>
        Property(s=>s.call_index).IsOptional();
        /// <summary>
        /// 父类别ID
        /// </summary>
        Property(s=>s.parent_id).IsOptional();
        /// <summary>
        /// 类别ID列表(逗号分隔开)
        /// </summary>
        Property(s=>s.class_list).IsOptional();
        /// <summary>
        /// 类别深度
        /// </summary>
        Property(s=>s.class_layer).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// URL跳转地址
        /// </summary>
        Property(s=>s.link_url).IsOptional();
        /// <summary>
        /// 图片地址
        /// </summary>
        Property(s=>s.img_url).IsOptional();
        /// <summary>
        /// 备注说明
        /// </summary>
        Property(s=>s.content).IsOptional();
        /// <summary>
        /// SEO标题
        /// </summary>
        Property(s=>s.seo_title).IsOptional();
        /// <summary>
        /// SEO关健字
        /// </summary>
        Property(s=>s.seo_keywords).IsOptional();
        /// <summary>
        /// SEO描述
        /// </summary>
        Property(s=>s.seo_description).IsOptional();
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_article_category");

		}
    }
}
