//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-article_comment 
    /// </summary>
	public class article_commentEntityTypeConfiguration :  EntityTypeConfiguration<article_comment>
    {
		public article_commentEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsOptional();
        /// <summary>
        /// 主表ID
        /// </summary>
        Property(s=>s.article_id).IsOptional();
        /// <summary>
        /// 父评论ID
        /// </summary>
        Property(s=>s.parent_id).IsOptional();
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 用户IP
        /// </summary>
        Property(s=>s.user_ip).IsOptional();
        /// <summary>
        /// 评论内容
        /// </summary>
        Property(s=>s.content).IsOptional();
        /// <summary>
        /// 是否锁定
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
        /// <summary>
        /// 发表时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
        /// <summary>
        /// 是否已答复
        /// </summary>
        Property(s=>s.is_reply).IsOptional();
        /// <summary>
        /// 答复内容
        /// </summary>
        Property(s=>s.reply_content).IsOptional();
        /// <summary>
        /// 回复时间
        /// </summary>
        Property(s=>s.reply_time).IsOptional();
 
			//配置表名称
			ToTable("dt_article_comment");

		}
    }
}
