//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-express 
    /// </summary>
	public class expressEntityTypeConfiguration :  EntityTypeConfiguration<express>
    {
		public expressEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 快递名称
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 物流编码
        /// </summary>
        Property(s=>s.express_code).IsOptional();
        /// <summary>
        /// 配送费用
        /// </summary>
        Property(s=>s.express_fee).IsOptional();
        /// <summary>
        /// 快递网址
        /// </summary>
        Property(s=>s.website).IsOptional();
        /// <summary>
        /// 备注说明
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 排序
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 是否不显示
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_express");

		}
    }
}
