//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-mail_template 
    /// </summary>
	public class mail_templateEntityTypeConfiguration :  EntityTypeConfiguration<mail_template>
    {
		public mail_templateEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 标题名称
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 调用别名
        /// </summary>
        Property(s=>s.call_index).IsOptional();
        /// <summary>
        /// 邮件标题
        /// </summary>
        Property(s=>s.maill_title).IsOptional();
        /// <summary>
        /// 邮件内容
        /// </summary>
        Property(s=>s.content).IsOptional();
        /// <summary>
        /// 系统默认
        /// </summary>
        Property(s=>s.is_sys).IsOptional();
 
			//配置表名称
			ToTable("dt_mail_template");

		}
    }
}
