//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-manager 
    /// </summary>
	public class managerEntityTypeConfiguration :  EntityTypeConfiguration<manager>
    {
		public managerEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 角色ID
        /// </summary>
        Property(s=>s.role_id).IsOptional();
        /// <summary>
        /// 管理员类型1超管2系管
        /// </summary>
        Property(s=>s.role_type).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 登录密码
        /// </summary>
        Property(s=>s.password).IsOptional();
        /// <summary>
        /// 6位随机字符串,加密用到
        /// </summary>
        Property(s=>s.salt).IsOptional();
        /// <summary>
        /// 管理员头像
        /// </summary>
        Property(s=>s.avatar).IsOptional();
        /// <summary>
        /// 用户昵称
        /// </summary>
        Property(s=>s.real_name).IsOptional();
        /// <summary>
        /// 联系电话
        /// </summary>
        Property(s=>s.telephone).IsOptional();
        /// <summary>
        /// 电子邮箱
        /// </summary>
        Property(s=>s.email).IsOptional();
        /// <summary>
        /// 
        /// </summary>
        Property(s=>s.is_audit).IsOptional();
        /// <summary>
        /// 是否锁定
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
        /// <summary>
        /// 添加时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_manager");

		}
    }
}
