//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-manager_log 
    /// </summary>
	public class manager_logEntityTypeConfiguration :  EntityTypeConfiguration<manager_log>
    {
		public manager_logEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 操作类型
        /// </summary>
        Property(s=>s.action_type).IsOptional();
        /// <summary>
        /// 备注
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 用户IP
        /// </summary>
        Property(s=>s.user_ip).IsOptional();
        /// <summary>
        /// 操作时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_manager_log");

		}
    }
}
