//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-oauth_app 
    /// </summary>
	public class oauth_appEntityTypeConfiguration :  EntityTypeConfiguration<oauth_app>
    {
		public oauth_appEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 标题
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 显示图片
        /// </summary>
        Property(s=>s.img_url).IsOptional();
        /// <summary>
        /// 描述
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 是否启用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
        /// <summary>
        /// 接口目录
        /// </summary>
        Property(s=>s.api_path).IsOptional();
 
			//配置表名称
			ToTable("dt_oauth_app");

		}
    }
}
