//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-order_goods 
    /// </summary>
	public class order_goodsEntityTypeConfiguration :  EntityTypeConfiguration<order_goods>
    {
		public order_goodsEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsOptional();
        /// <summary>
        /// 文章ID
        /// </summary>
        Property(s=>s.article_id).IsOptional();
        /// <summary>
        /// 订单ID
        /// </summary>
        Property(s=>s.order_id).IsOptional();
        /// <summary>
        /// 商品ID
        /// </summary>
        Property(s=>s.goods_id).IsOptional();
        /// <summary>
        /// 商品货号
        /// </summary>
        Property(s=>s.goods_no).IsOptional();
        /// <summary>
        /// 商品标题
        /// </summary>
        Property(s=>s.goods_title).IsOptional();
        /// <summary>
        /// 商品图片
        /// </summary>
        Property(s=>s.img_url).IsOptional();
        /// <summary>
        /// 商品价格
        /// </summary>
        Property(s=>s.goods_price).IsOptional();
        /// <summary>
        /// 实际价格
        /// </summary>
        Property(s=>s.real_price).IsOptional();
        /// <summary>
        /// 订购数量
        /// </summary>
        Property(s=>s.quantity).IsOptional();
        /// <summary>
        /// 积分,正数赠送|负数消费
        /// </summary>
        Property(s=>s.point).IsOptional();
 
			//配置表名称
			ToTable("dt_order_goods");

		}
    }
}
