//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-orders 
    /// </summary>
	public class ordersEntityTypeConfiguration :  EntityTypeConfiguration<orders>
    {
		public ordersEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// 订单号
        /// </summary>
        Property(s=>s.order_no).IsOptional();
        /// <summary>
        /// 交易号担保支付用到
        /// </summary>
        Property(s=>s.trade_no).IsOptional();
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 支付方式
        /// </summary>
        Property(s=>s.payment_id).IsOptional();
        /// <summary>
        /// 支付手续费
        /// </summary>
        Property(s=>s.payment_fee).IsOptional();
        /// <summary>
        /// 支付状态0未支付1待支付2已支付
        /// </summary>
        Property(s=>s.payment_status).IsOptional();
        /// <summary>
        /// 支付时间
        /// </summary>
        Property(s=>s.payment_time).IsOptional();
        /// <summary>
        /// 快递ID
        /// </summary>
        Property(s=>s.express_id).IsOptional();
        /// <summary>
        /// 快递单号
        /// </summary>
        Property(s=>s.express_no).IsOptional();
        /// <summary>
        /// 物流费用
        /// </summary>
        Property(s=>s.express_fee).IsOptional();
        /// <summary>
        /// 发货状态1未发货2已发货
        /// </summary>
        Property(s=>s.express_status).IsOptional();
        /// <summary>
        /// 发货时间
        /// </summary>
        Property(s=>s.express_time).IsOptional();
        /// <summary>
        /// 收货人姓名
        /// </summary>
        Property(s=>s.accept_name).IsOptional();
        /// <summary>
        /// 邮政编码
        /// </summary>
        Property(s=>s.post_code).IsOptional();
        /// <summary>
        /// 联系电话
        /// </summary>
        Property(s=>s.telphone).IsOptional();
        /// <summary>
        /// 手机
        /// </summary>
        Property(s=>s.mobile).IsOptional();
        /// <summary>
        /// 邮箱
        /// </summary>
        Property(s=>s.email).IsOptional();
        /// <summary>
        /// 所属省市区
        /// </summary>
        Property(s=>s.area).IsOptional();
        /// <summary>
        /// 收货地址
        /// </summary>
        Property(s=>s.address).IsOptional();
        /// <summary>
        /// 订单留言
        /// </summary>
        Property(s=>s.message).IsOptional();
        /// <summary>
        /// 订单备注
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 是否索要发票
        /// </summary>
        Property(s=>s.is_invoice).IsOptional();
        /// <summary>
        /// 发票抬头
        /// </summary>
        Property(s=>s.invoice_title).IsOptional();
        /// <summary>
        /// 税金
        /// </summary>
        Property(s=>s.invoice_taxes).IsOptional();
        /// <summary>
        /// 应付商品总金额
        /// </summary>
        Property(s=>s.payable_amount).IsOptional();
        /// <summary>
        /// 实付商品总金额
        /// </summary>
        Property(s=>s.real_amount).IsOptional();
        /// <summary>
        /// 订单总金额
        /// </summary>
        Property(s=>s.order_amount).IsOptional();
        /// <summary>
        /// 积分,正数赠送|负数消费
        /// </summary>
        Property(s=>s.point).IsOptional();
        /// <summary>
        /// 订单状态1生成订单,2确认订单,3完成订单,4取消订单,5作废订单
        /// </summary>
        Property(s=>s.status).IsOptional();
        /// <summary>
        /// 下单时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
        /// <summary>
        /// 确认时间
        /// </summary>
        Property(s=>s.confirm_time).IsOptional();
        /// <summary>
        /// 订单完成时间
        /// </summary>
        Property(s=>s.complete_time).IsOptional();
 
			//配置表名称
			ToTable("dt_orders");

		}
    }
}
