//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-payment 
    /// </summary>
	public class paymentEntityTypeConfiguration :  EntityTypeConfiguration<payment>
    {
		public paymentEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 支付名称
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 显示图片
        /// </summary>
        Property(s=>s.img_url).IsOptional();
        /// <summary>
        /// 备注说明
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 支付类型1线上2线下
        /// </summary>
        Property(s=>s.type).IsOptional();
        /// <summary>
        /// 手续费类型1百分比2固定金额
        /// </summary>
        Property(s=>s.poundage_type).IsOptional();
        /// <summary>
        /// 手续费金额
        /// </summary>
        Property(s=>s.poundage_amount).IsOptional();
        /// <summary>
        /// API目录名
        /// </summary>
        Property(s=>s.api_path).IsOptional();
        /// <summary>
        /// 支付链接页面
        /// </summary>
        Property(s=>s.redirect_url).IsOptional();
        /// <summary>
        /// 跳转返回页面
        /// </summary>
        Property(s=>s.return_url).IsOptional();
        /// <summary>
        /// 支付通知页面
        /// </summary>
        Property(s=>s.notify_url).IsOptional();
        /// <summary>
        /// 排序
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 是否启用0正常1禁用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_payment");

		}
    }
}
