//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-sites 
    /// </summary>
	public class sitesEntityTypeConfiguration :  EntityTypeConfiguration<sites>
    {
		public sitesEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 标题
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 站点目录名
        /// </summary>
        Property(s=>s.build_path).IsOptional();
        /// <summary>
        /// 模板目录名
        /// </summary>
        Property(s=>s.templet_path).IsOptional();
        /// <summary>
        /// 绑定域名
        /// </summary>
        Property(s=>s.domain).IsOptional();
        /// <summary>
        /// 是否默认站
        /// </summary>
        Property(s=>s.is_default).IsOptional();
        /// <summary>
        /// 网站名称
        /// </summary>
        Property(s=>s.name).IsOptional();
        /// <summary>
        /// 网站LOGO
        /// </summary>
        Property(s=>s.logo).IsOptional();
        /// <summary>
        /// 公司名称
        /// </summary>
        Property(s=>s.company).IsOptional();
        /// <summary>
        /// 通讯地址
        /// </summary>
        Property(s=>s.address).IsOptional();
        /// <summary>
        /// 联系电话
        /// </summary>
        Property(s=>s.tel).IsOptional();
        /// <summary>
        /// 传真号码
        /// </summary>
        Property(s=>s.fax).IsOptional();
        /// <summary>
        /// 电子邮箱
        /// </summary>
        Property(s=>s.email).IsOptional();
        /// <summary>
        /// 备案号
        /// </summary>
        Property(s=>s.crod).IsOptional();
        /// <summary>
        /// 版权信息
        /// </summary>
        Property(s=>s.copyright).IsOptional();
        /// <summary>
        /// SEO标题
        /// </summary>
        Property(s=>s.seo_title).IsOptional();
        /// <summary>
        /// SEO关健字
        /// </summary>
        Property(s=>s.seo_keyword).IsOptional();
        /// <summary>
        /// SEO描述
        /// </summary>
        Property(s=>s.seo_description).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_sites");

		}
    }
}
