//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-site_channel 
    /// </summary>
	public class site_channelEntityTypeConfiguration :  EntityTypeConfiguration<site_channel>
    {
		public site_channelEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// 频道名称
        /// </summary>
        Property(s=>s.name).IsOptional();
        /// <summary>
        /// 频道标题
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// 否开启评论
        /// </summary>
        Property(s=>s.is_comment).IsOptional();
        /// <summary>
        /// 是否开启相册功能
        /// </summary>
        Property(s=>s.is_albums).IsOptional();
        /// <summary>
        /// 是否开启附件功能
        /// </summary>
        Property(s=>s.is_attach).IsOptional();
        /// <summary>
        /// 是否开启价格
        /// </summary>
        Property(s=>s.is_spec).IsOptional();
        /// <summary>
        /// 是否允许投稿
        /// </summary>
        Property(s=>s.is_contribute).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 状态0启用1禁用
        /// </summary>
        Property(s=>s.is_lock).IsOptional();
 
			//配置表名称
			ToTable("dt_site_channel");

		}
    }
}
