//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-site_oauth 
    /// </summary>
	public class site_oauthEntityTypeConfiguration :  EntityTypeConfiguration<site_oauth>
    {
		public site_oauthEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// OAuth应用ID
        /// </summary>
        Property(s=>s.oauth_id).IsOptional();
        /// <summary>
        /// 自定义标签
        /// </summary>
        Property(s=>s.title).IsOptional();
        /// <summary>
        /// AppId
        /// </summary>
        Property(s=>s.app_id).IsOptional();
        /// <summary>
        /// AppKey
        /// </summary>
        Property(s=>s.app_key).IsOptional();
        /// <summary>
        /// 排序数字
        /// </summary>
        Property(s=>s.sort_id).IsOptional();
        /// <summary>
        /// 添加时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_site_oauth");

		}
    }
}
