//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-user_login_log 
    /// </summary>
	public class user_login_logEntityTypeConfiguration :  EntityTypeConfiguration<user_login_log>
    {
		public user_login_logEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 备注说明
        /// </summary>
        Property(s=>s.remark).IsOptional();
        /// <summary>
        /// 登录时间
        /// </summary>
        Property(s=>s.login_time).IsOptional();
        /// <summary>
        /// 登录IP
        /// </summary>
        Property(s=>s.login_ip).IsOptional();
 
			//配置表名称
			ToTable("dt_user_login_log");

		}
    }
}
