//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-user_oauth 
    /// </summary>
	public class user_oauthEntityTypeConfiguration :  EntityTypeConfiguration<user_oauth>
    {
		public user_oauthEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 开放平台名称
        /// </summary>
        Property(s=>s.oauth_name).IsRequired();
        /// <summary>
        /// access_token
        /// </summary>
        Property(s=>s.oauth_access_token).IsOptional();
        /// <summary>
        /// 授权key
        /// </summary>
        Property(s=>s.oauth_openid).IsOptional();
        /// <summary>
        /// 授权时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_user_oauth");

		}
    }
}
