//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-user_group_price 
    /// </summary>
	public class user_group_priceEntityTypeConfiguration :  EntityTypeConfiguration<user_group_price>
    {
		public user_group_priceEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 频道ID
        /// </summary>
        Property(s=>s.channel_id).IsOptional();
        /// <summary>
        /// 文章ID
        /// </summary>
        Property(s=>s.article_id).IsOptional();
        /// <summary>
        /// 会员组ID
        /// </summary>
        Property(s=>s.group_id).IsOptional();
        /// <summary>
        /// 价格
        /// </summary>
        Property(s=>s.price).IsOptional();
 
			//配置表名称
			ToTable("dt_user_group_price");

		}
    }
}
