//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-user_addr_book 
    /// </summary>
	public class user_addr_bookEntityTypeConfiguration :  EntityTypeConfiguration<user_addr_book>
    {
		public user_addr_bookEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 用户ID
        /// </summary>
        Property(s=>s.user_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsOptional();
        /// <summary>
        /// 收件人
        /// </summary>
        Property(s=>s.accept_name).IsOptional();
        /// <summary>
        /// 省市区逗号分隔
        /// </summary>
        Property(s=>s.area).IsOptional();
        /// <summary>
        /// 详细地址
        /// </summary>
        Property(s=>s.address).IsOptional();
        /// <summary>
        /// 手机号码
        /// </summary>
        Property(s=>s.mobile).IsOptional();
        /// <summary>
        /// 电话号码
        /// </summary>
        Property(s=>s.telphone).IsOptional();
        /// <summary>
        /// 电子邮箱
        /// </summary>
        Property(s=>s.email).IsOptional();
        /// <summary>
        /// 邮政编码
        /// </summary>
        Property(s=>s.post_code).IsOptional();
        /// <summary>
        /// 是否默认
        /// </summary>
        Property(s=>s.is_default).IsOptional();
        /// <summary>
        /// 添加时间
        /// </summary>
        Property(s=>s.add_time).IsOptional();
 
			//配置表名称
			ToTable("dt_user_addr_book");

		}
    }
}
