//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace EFFramework
{   
    /// <summary>
    /// 实体-users 
    /// </summary>
	public class usersEntityTypeConfiguration :  EntityTypeConfiguration<users>
    {
		public usersEntityTypeConfiguration()
		{
			/// <summary>
        /// 自增ID
        /// </summary>
        HasKey(s => s.id);
        Property(s=>s.id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        /// <summary>
        /// 站点ID
        /// </summary>
        Property(s=>s.site_id).IsOptional();
        /// <summary>
        /// 用户组ID
        /// </summary>
        Property(s=>s.group_id).IsOptional();
        /// <summary>
        /// 用户名
        /// </summary>
        Property(s=>s.user_name).IsRequired();
        /// <summary>
        /// 6位随机字符串,加密用到
        /// </summary>
        Property(s=>s.salt).IsOptional();
        /// <summary>
        /// 用户密码
        /// </summary>
        Property(s=>s.password).IsRequired();
        /// <summary>
        /// 手机号码
        /// </summary>
        Property(s=>s.mobile).IsOptional();
        /// <summary>
        /// 电子邮箱
        /// </summary>
        Property(s=>s.email).IsOptional();
        /// <summary>
        /// 用户头像
        /// </summary>
        Property(s=>s.avatar).IsOptional();
        /// <summary>
        /// 用户昵称
        /// </summary>
        Property(s=>s.nick_name).IsOptional();
        /// <summary>
        /// 性别
        /// </summary>
        Property(s=>s.sex).IsOptional();
        /// <summary>
        /// 生日
        /// </summary>
        Property(s=>s.birthday).IsOptional();
        /// <summary>
        /// 电话
        /// </summary>
        Property(s=>s.telphone).IsOptional();
        /// <summary>
        /// 所属地区逗号分隔
        /// </summary>
        Property(s=>s.area).IsOptional();
        /// <summary>
        /// 详情地址
        /// </summary>
        Property(s=>s.address).IsOptional();
        /// <summary>
        /// QQ号码
        /// </summary>
        Property(s=>s.qq).IsOptional();
        /// <summary>
        /// MSN号码
        /// </summary>
        Property(s=>s.msn).IsOptional();
        /// <summary>
        /// 账户余额
        /// </summary>
        Property(s=>s.amount).IsOptional();
        /// <summary>
        /// 账户积分
        /// </summary>
        Property(s=>s.point).IsOptional();
        /// <summary>
        /// 升级经验值
        /// </summary>
        Property(s=>s.exp).IsOptional();
        /// <summary>
        /// 账户状态,0正常,1待验证,2待审核,3锁定
        /// </summary>
        Property(s=>s.status).IsOptional();
        /// <summary>
        /// 注册时间
        /// </summary>
        Property(s=>s.reg_time).IsOptional();
        /// <summary>
        /// 注册IP
        /// </summary>
        Property(s=>s.reg_ip).IsOptional();
 
			//配置表名称
			ToTable("dt_users");

		}
    }
}
