//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_comment 
    /// </summary>
	public class article_comment :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int site_id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 主表ID
        /// </summary>
         public int article_id{ get; set; }
        /// <summary>
        /// 父评论ID
        /// </summary>
         public int parent_id{ get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
         public int user_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 用户IP
        /// </summary>
         public string user_ip{ get; set; }
        /// <summary>
        /// 评论内容
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// 是否锁定
        /// </summary>
         public byte is_lock{ get; set; }
        /// <summary>
        /// 发表时间
        /// </summary>
         public DateTime add_time{ get; set; }
        /// <summary>
        /// 是否已答复
        /// </summary>
         public byte is_reply{ get; set; }
        /// <summary>
        /// 答复内容
        /// </summary>
         public string reply_content{ get; set; }
        /// <summary>
        /// 回复时间
        /// </summary>
         public DateTime reply_time{ get; set; }
 

	}
}
