//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_attach 
    /// </summary>
	public class article_attach :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 文章ID
        /// </summary>
         public int article_id{ get; set; }
        /// <summary>
        /// 文件名
        /// </summary>
         public string file_name{ get; set; }
        /// <summary>
        /// 文件路径
        /// </summary>
         public string file_path{ get; set; }
        /// <summary>
        /// 文件大小(字节)
        /// </summary>
         public int file_size{ get; set; }
        /// <summary>
        /// 文件扩展名
        /// </summary>
         public string file_ext{ get; set; }
        /// <summary>
        /// 下载次数
        /// </summary>
         public int down_num{ get; set; }
        /// <summary>
        /// 积分(正赠送负消费)
        /// </summary>
         public int point{ get; set; }
        /// <summary>
        /// 上传时间
        /// </summary>
         public DateTime add_time{ get; set; }
 

	}
}
