//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_tags_relation 
    /// </summary>
	public class article_tags_relation :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 文章ID
        /// </summary>
         public int article_id{ get; set; }
        /// <summary>
        /// 标签ID
        /// </summary>
         public int tag_id{ get; set; }
 

	}
}
