//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_tags 
    /// </summary>
	public class article_tags :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 是否推荐
        /// </summary>
         public byte is_red{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int sort_id{ get; set; }
        /// <summary>
        /// 时间
        /// </summary>
         public DateTime add_time{ get; set; }
 

	}
}
