//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_albums 
    /// </summary>
	public class article_albums :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int? channel_id{ get; set; }
        /// <summary>
        /// 文章ID
        /// </summary>
         public int? article_id{ get; set; }
        /// <summary>
        /// 缩略图地址
        /// </summary>
         public string thumb_path{ get; set; }
        /// <summary>
        /// 原图地址
        /// </summary>
         public string original_path{ get; set; }
        /// <summary>
        /// 图片描述
        /// </summary>
         public string remark{ get; set; }
        /// <summary>
        /// 上传时间
        /// </summary>
         public DateTime? add_time{ get; set; }
 

	}
}
