//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_attribute_field 
    /// </summary>
	public class article_attribute_field :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 列名
        /// </summary>
         public string name{ get; set; }
        /// <summary>
        /// 标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 控件类型
        /// </summary>
         public string control_type{ get; set; }
        /// <summary>
        /// 字段类型
        /// </summary>
         public string data_type{ get; set; }
        /// <summary>
        /// 字段长度
        /// </summary>
         public int? data_length{ get; set; }
        /// <summary>
        /// 小数点位数
        /// </summary>
         public byte? data_place{ get; set; }
        /// <summary>
        /// 选项列表
        /// </summary>
         public string item_option{ get; set; }
        /// <summary>
        /// 默认值
        /// </summary>
         public string default_value{ get; set; }
        /// <summary>
        /// 是否必填0非必填1必填
        /// </summary>
         public byte? is_required{ get; set; }
        /// <summary>
        /// 是否密码框
        /// </summary>
         public byte? is_password{ get; set; }
        /// <summary>
        /// 是否允许HTML
        /// </summary>
         public byte? is_html{ get; set; }
        /// <summary>
        /// 编辑器类型0标准型1简洁型
        /// </summary>
         public byte? editor_type{ get; set; }
        /// <summary>
        /// 验证提示信息
        /// </summary>
         public string valid_tip_msg{ get; set; }
        /// <summary>
        /// 验证失败提示信息
        /// </summary>
         public string valid_error_msg{ get; set; }
        /// <summary>
        /// 验证正则表达式
        /// </summary>
         public string valid_pattern{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int? sort_id{ get; set; }
        /// <summary>
        /// 系统默认
        /// </summary>
         public byte? is_sys{ get; set; }
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
         public byte? is_lock{ get; set; }
 

	}
}
