//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_article_category 
    /// </summary>
	public class article_category :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int? site_id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 类别标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 调用别名
        /// </summary>
         public string call_index{ get; set; }
        /// <summary>
        /// 父类别ID
        /// </summary>
         public int? parent_id{ get; set; }
        /// <summary>
        /// 类别ID列表(逗号分隔开)
        /// </summary>
         public string class_list{ get; set; }
        /// <summary>
        /// 类别深度
        /// </summary>
         public int? class_layer{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int? sort_id{ get; set; }
        /// <summary>
        /// URL跳转地址
        /// </summary>
         public string link_url{ get; set; }
        /// <summary>
        /// 图片地址
        /// </summary>
         public string img_url{ get; set; }
        /// <summary>
        /// 备注说明
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// SEO标题
        /// </summary>
         public string seo_title{ get; set; }
        /// <summary>
        /// SEO关健字
        /// </summary>
         public string seo_keywords{ get; set; }
        /// <summary>
        /// SEO描述
        /// </summary>
         public string seo_description{ get; set; }
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
         public byte? is_lock{ get; set; }
 

	}
}
