//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_channel_article_goods 
    /// </summary>
	public class channel_article_goods :  IBaseEntity
	{
   
			/// <summary>
        /// 
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int site_id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int category_id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string call_index{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string link_url{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string img_url{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string seo_title{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string seo_keywords{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string seo_description{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string tags{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string zhaiyao{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int sort_id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int click{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int status{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_msg{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_top{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_red{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_hot{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_slide{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int is_sys{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int like_count{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public DateTime add_time{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public DateTime update_time{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string sub_title{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string goods_no{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int stock_quantity{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public decimal market_price{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public decimal sell_price{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int point{ get; set; }
 

	}
}
