//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_feedback 
    /// </summary>
	public class feedback :  IBaseEntity
	{
   
			/// <summary>
        /// 
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public int site_id{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string user_tel{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string user_qq{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string user_email{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public DateTime add_time{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public string reply_content{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public DateTime? reply_time{ get; set; }
        /// <summary>
        /// 
        /// </summary>
         public byte is_lock{ get; set; }
 

	}
}
