//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_manager_role_value 
    /// </summary>
	public class manager_role_value :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 角色ID
        /// </summary>
         public int? role_id{ get; set; }
        /// <summary>
        /// 导航名称
        /// </summary>
         public string nav_name{ get; set; }
        /// <summary>
        /// 权限类型
        /// </summary>
         public string action_type{ get; set; }
 

	}
}
