//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_manager_role 
    /// </summary>
	public class manager_role :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
         public string role_name{ get; set; }
        /// <summary>
        /// 角色类型
        /// </summary>
         public byte? role_type{ get; set; }
        /// <summary>
        /// 是否系统默认0否1是
        /// </summary>
         public byte? is_sys{ get; set; }
 

	}
}
