//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_oauth_app 
    /// </summary>
	public class oauth_app :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 显示图片
        /// </summary>
         public string img_url{ get; set; }
        /// <summary>
        /// 描述
        /// </summary>
         public string remark{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int sort_id{ get; set; }
        /// <summary>
        /// 是否启用
        /// </summary>
         public byte is_lock{ get; set; }
        /// <summary>
        /// 接口目录
        /// </summary>
         public string api_path{ get; set; }
 

	}
}
