//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_order_goods 
    /// </summary>
	public class order_goods :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 频道ID
        /// </summary>
         public int channel_id{ get; set; }
        /// <summary>
        /// 文章ID
        /// </summary>
         public int article_id{ get; set; }
        /// <summary>
        /// 订单ID
        /// </summary>
         public int order_id{ get; set; }
        /// <summary>
        /// 商品ID
        /// </summary>
         public int goods_id{ get; set; }
        /// <summary>
        /// 商品货号
        /// </summary>
         public string goods_no{ get; set; }
        /// <summary>
        /// 商品标题
        /// </summary>
         public string goods_title{ get; set; }
        /// <summary>
        /// 商品图片
        /// </summary>
         public string img_url{ get; set; }
        /// <summary>
        /// 商品价格
        /// </summary>
         public decimal goods_price{ get; set; }
        /// <summary>
        /// 实际价格
        /// </summary>
         public decimal real_price{ get; set; }
        /// <summary>
        /// 订购数量
        /// </summary>
         public int quantity{ get; set; }
        /// <summary>
        /// 积分,正数赠送|负数消费
        /// </summary>
         public int point{ get; set; }
 

	}
}
