//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_orders 
    /// </summary>
	public class orders :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int? site_id{ get; set; }
        /// <summary>
        /// 订单号
        /// </summary>
         public string order_no{ get; set; }
        /// <summary>
        /// 交易号担保支付用到
        /// </summary>
         public string trade_no{ get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
         public int? user_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 支付方式
        /// </summary>
         public int? payment_id{ get; set; }
        /// <summary>
        /// 支付手续费
        /// </summary>
         public decimal? payment_fee{ get; set; }
        /// <summary>
        /// 支付状态0未支付1待支付2已支付
        /// </summary>
         public byte? payment_status{ get; set; }
        /// <summary>
        /// 支付时间
        /// </summary>
         public DateTime? payment_time{ get; set; }
        /// <summary>
        /// 快递ID
        /// </summary>
         public int? express_id{ get; set; }
        /// <summary>
        /// 快递单号
        /// </summary>
         public string express_no{ get; set; }
        /// <summary>
        /// 物流费用
        /// </summary>
         public decimal? express_fee{ get; set; }
        /// <summary>
        /// 发货状态1未发货2已发货
        /// </summary>
         public byte? express_status{ get; set; }
        /// <summary>
        /// 发货时间
        /// </summary>
         public DateTime? express_time{ get; set; }
        /// <summary>
        /// 收货人姓名
        /// </summary>
         public string accept_name{ get; set; }
        /// <summary>
        /// 邮政编码
        /// </summary>
         public string post_code{ get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
         public string telphone{ get; set; }
        /// <summary>
        /// 手机
        /// </summary>
         public string mobile{ get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
         public string email{ get; set; }
        /// <summary>
        /// 所属省市区
        /// </summary>
         public string area{ get; set; }
        /// <summary>
        /// 收货地址
        /// </summary>
         public string address{ get; set; }
        /// <summary>
        /// 订单留言
        /// </summary>
         public string message{ get; set; }
        /// <summary>
        /// 订单备注
        /// </summary>
         public string remark{ get; set; }
        /// <summary>
        /// 是否索要发票
        /// </summary>
         public byte? is_invoice{ get; set; }
        /// <summary>
        /// 发票抬头
        /// </summary>
         public string invoice_title{ get; set; }
        /// <summary>
        /// 税金
        /// </summary>
         public decimal? invoice_taxes{ get; set; }
        /// <summary>
        /// 应付商品总金额
        /// </summary>
         public decimal? payable_amount{ get; set; }
        /// <summary>
        /// 实付商品总金额
        /// </summary>
         public decimal? real_amount{ get; set; }
        /// <summary>
        /// 订单总金额
        /// </summary>
         public decimal? order_amount{ get; set; }
        /// <summary>
        /// 积分,正数赠送|负数消费
        /// </summary>
         public int? point{ get; set; }
        /// <summary>
        /// 订单状态1生成订单,2确认订单,3完成订单,4取消订单,5作废订单
        /// </summary>
         public byte? status{ get; set; }
        /// <summary>
        /// 下单时间
        /// </summary>
         public DateTime? add_time{ get; set; }
        /// <summary>
        /// 确认时间
        /// </summary>
         public DateTime? confirm_time{ get; set; }
        /// <summary>
        /// 订单完成时间
        /// </summary>
         public DateTime? complete_time{ get; set; }
 

	}
}
