//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_site_oauth 
    /// </summary>
	public class site_oauth :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int site_id{ get; set; }
        /// <summary>
        /// OAuth应用ID
        /// </summary>
         public int oauth_id{ get; set; }
        /// <summary>
        /// 自定义标签
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// AppId
        /// </summary>
         public string app_id{ get; set; }
        /// <summary>
        /// AppKey
        /// </summary>
         public string app_key{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int sort_id{ get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
         public DateTime add_time{ get; set; }
 

	}
}
