//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_sites 
    /// </summary>
	public class sites :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 站点目录名
        /// </summary>
         public string build_path{ get; set; }
        /// <summary>
        /// 模板目录名
        /// </summary>
         public string templet_path{ get; set; }
        /// <summary>
        /// 绑定域名
        /// </summary>
         public string domain{ get; set; }
        /// <summary>
        /// 是否默认站
        /// </summary>
         public byte? is_default{ get; set; }
        /// <summary>
        /// 网站名称
        /// </summary>
         public string name{ get; set; }
        /// <summary>
        /// 网站LOGO
        /// </summary>
         public string logo{ get; set; }
        /// <summary>
        /// 公司名称
        /// </summary>
         public string company{ get; set; }
        /// <summary>
        /// 通讯地址
        /// </summary>
         public string address{ get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
         public string tel{ get; set; }
        /// <summary>
        /// 传真号码
        /// </summary>
         public string fax{ get; set; }
        /// <summary>
        /// 电子邮箱
        /// </summary>
         public string email{ get; set; }
        /// <summary>
        /// 备案号
        /// </summary>
         public string crod{ get; set; }
        /// <summary>
        /// 版权信息
        /// </summary>
         public string copyright{ get; set; }
        /// <summary>
        /// SEO标题
        /// </summary>
         public string seo_title{ get; set; }
        /// <summary>
        /// SEO关健字
        /// </summary>
         public string seo_keyword{ get; set; }
        /// <summary>
        /// SEO描述
        /// </summary>
         public string seo_description{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int? sort_id{ get; set; }
        /// <summary>
        /// 状态0正常1禁用
        /// </summary>
         public byte? is_lock{ get; set; }
 

	}
}
