//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_site_channel 
    /// </summary>
	public class site_channel :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int? site_id{ get; set; }
        /// <summary>
        /// 频道名称
        /// </summary>
         public string name{ get; set; }
        /// <summary>
        /// 频道标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 否开启评论
        /// </summary>
         public byte? is_comment{ get; set; }
        /// <summary>
        /// 是否开启相册功能
        /// </summary>
         public byte? is_albums{ get; set; }
        /// <summary>
        /// 是否开启附件功能
        /// </summary>
         public byte? is_attach{ get; set; }
        /// <summary>
        /// 是否开启价格
        /// </summary>
         public byte? is_spec{ get; set; }
        /// <summary>
        /// 是否允许投稿
        /// </summary>
         public byte? is_contribute{ get; set; }
        /// <summary>
        /// 排序数字
        /// </summary>
         public int? sort_id{ get; set; }
        /// <summary>
        /// 状态0启用1禁用
        /// </summary>
         public byte? is_lock{ get; set; }
 

	}
}
