//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_sms_template 
    /// </summary>
	public class sms_template :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 调用别名
        /// </summary>
         public string call_index{ get; set; }
        /// <summary>
        /// 短信内容
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// 系统默认
        /// </summary>
         public byte is_sys{ get; set; }
 

	}
}
