//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_user_groups 
    /// </summary>
	public class user_groups :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 组别名称
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 会员等级值
        /// </summary>
         public int grade{ get; set; }
        /// <summary>
        /// 升级经验值
        /// </summary>
         public int upgrade_exp{ get; set; }
        /// <summary>
        /// 默认预存款
        /// </summary>
         public decimal amount{ get; set; }
        /// <summary>
        /// 默认积分
        /// </summary>
         public int point{ get; set; }
        /// <summary>
        /// 购物折扣
        /// </summary>
         public int discount{ get; set; }
        /// <summary>
        /// 是否注册用户组
        /// </summary>
         public byte is_default{ get; set; }
        /// <summary>
        /// 是否自动升级
        /// </summary>
         public byte is_upgrade{ get; set; }
        /// <summary>
        /// 是否禁用
        /// </summary>
         public byte is_lock{ get; set; }
 

	}
}
