//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_user_addr_book 
    /// </summary>
	public class user_addr_book :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
         public int user_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 收件人
        /// </summary>
         public string accept_name{ get; set; }
        /// <summary>
        /// 省市区逗号分隔
        /// </summary>
         public string area{ get; set; }
        /// <summary>
        /// 详细地址
        /// </summary>
         public string address{ get; set; }
        /// <summary>
        /// 手机号码
        /// </summary>
         public string mobile{ get; set; }
        /// <summary>
        /// 电话号码
        /// </summary>
         public string telphone{ get; set; }
        /// <summary>
        /// 电子邮箱
        /// </summary>
         public string email{ get; set; }
        /// <summary>
        /// 邮政编码
        /// </summary>
         public string post_code{ get; set; }
        /// <summary>
        /// 是否默认
        /// </summary>
         public byte is_default{ get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
         public DateTime add_time{ get; set; }
 

	}
}
