//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_user_code 
    /// </summary>
	public class user_code :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
         public int? user_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 生成码类别 password取回密码,register邀请注册
        /// </summary>
         public string type{ get; set; }
        /// <summary>
        /// 生成的字符串
        /// </summary>
         public string str_code{ get; set; }
        /// <summary>
        /// 使用次数
        /// </summary>
         public int? count{ get; set; }
        /// <summary>
        /// 状态0未使用1已使用
        /// </summary>
         public byte? status{ get; set; }
        /// <summary>
        /// 用户IP
        /// </summary>
         public string user_ip{ get; set; }
        /// <summary>
        /// 有效时间
        /// </summary>
         public DateTime eff_time{ get; set; }
        /// <summary>
        /// 生成时间
        /// </summary>
         public DateTime add_time{ get; set; }
 

	}
}
