//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_user_message 
    /// </summary>
	public class user_message :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 短信息类型0系统消息1收件箱2发件箱
        /// </summary>
         public byte type{ get; set; }
        /// <summary>
        /// 发件人
        /// </summary>
         public string post_user_name{ get; set; }
        /// <summary>
        /// 收件人
        /// </summary>
         public string accept_user_name{ get; set; }
        /// <summary>
        /// 是否查看0未阅1已阅
        /// </summary>
         public byte is_read{ get; set; }
        /// <summary>
        /// 短信息标题
        /// </summary>
         public string title{ get; set; }
        /// <summary>
        /// 短信息内容
        /// </summary>
         public string content{ get; set; }
        /// <summary>
        /// 发送时间
        /// </summary>
         public DateTime post_time{ get; set; }
        /// <summary>
        /// 阅读时间
        /// </summary>
         public DateTime read_time{ get; set; }
 

	}
}
