//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_users 
    /// </summary>
	public class users :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 站点ID
        /// </summary>
         public int? site_id{ get; set; }
        /// <summary>
        /// 用户组ID
        /// </summary>
         public int? group_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 6位随机字符串,加密用到
        /// </summary>
         public string salt{ get; set; }
        /// <summary>
        /// 用户密码
        /// </summary>
         public string password{ get; set; }
        /// <summary>
        /// 手机号码
        /// </summary>
         public string mobile{ get; set; }
        /// <summary>
        /// 电子邮箱
        /// </summary>
         public string email{ get; set; }
        /// <summary>
        /// 用户头像
        /// </summary>
         public string avatar{ get; set; }
        /// <summary>
        /// 用户昵称
        /// </summary>
         public string nick_name{ get; set; }
        /// <summary>
        /// 性别
        /// </summary>
         public string sex{ get; set; }
        /// <summary>
        /// 生日
        /// </summary>
         public DateTime? birthday{ get; set; }
        /// <summary>
        /// 电话
        /// </summary>
         public string telphone{ get; set; }
        /// <summary>
        /// 所属地区逗号分隔
        /// </summary>
         public string area{ get; set; }
        /// <summary>
        /// 详情地址
        /// </summary>
         public string address{ get; set; }
        /// <summary>
        /// QQ号码
        /// </summary>
         public string qq{ get; set; }
        /// <summary>
        /// MSN号码
        /// </summary>
         public string msn{ get; set; }
        /// <summary>
        /// 账户余额
        /// </summary>
         public decimal? amount{ get; set; }
        /// <summary>
        /// 账户积分
        /// </summary>
         public int? point{ get; set; }
        /// <summary>
        /// 升级经验值
        /// </summary>
         public int? exp{ get; set; }
        /// <summary>
        /// 账户状态,0正常,1待验证,2待审核,3锁定
        /// </summary>
         public byte? status{ get; set; }
        /// <summary>
        /// 注册时间
        /// </summary>
         public DateTime? reg_time{ get; set; }
        /// <summary>
        /// 注册IP
        /// </summary>
         public string reg_ip{ get; set; }
 

	}
}
