//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Models
{   
    /// <summary>
    /// 实体-dt_user_login_log 
    /// </summary>
	public class user_login_log :  IBaseEntity
	{
   
			/// <summary>
        /// 自增ID
        /// </summary>
         public int id{ get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
         public int user_id{ get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
         public string user_name{ get; set; }
        /// <summary>
        /// 备注说明
        /// </summary>
         public string remark{ get; set; }
        /// <summary>
        /// 登录时间
        /// </summary>
         public DateTime login_time{ get; set; }
        /// <summary>
        /// 登录IP
        /// </summary>
         public string login_ip{ get; set; }
 

	}
}
